#### ShoppingCartController.Get
GET http://localhost:5214/shopping-cart/100

#### ShoppingCartController.Post
POST http://localhost:5214/shopping-cart/100/items
Accept: application/json
Content-Type: application/json

[1, 2]

#### EventController.Get
GET http://localhost:5214/event